alias ..='cd ..'
alias ...='cd ../..'

alias l='ls -alh'
alias lb='ls -alh | bat'
alias lfa='ls -alh | fzf | awk -v pwd="$(pwd)" "{print pwd \"/\" \$9}" | copyme'
alias lg='ls -alh | grep'
alias lgd='ls -alh | grep ^d'
alias lgf='ls -alh | grep ^-'
alias lgi='ls -alh | grep -i'

alias rm='rm -vrfI'
alias cp='cp -vr'
alias mv='mv -v'
alias mkdir='mkdir -vp'

alias grep='grep --color=auto'

alias g='git'
alias ga='git add'
alias gaA='git add -A'
alias gau='git add -u'
alias gs='git status'
alias gco='git co'
alias gcoc='git coc'
alias gcob='git cob'
alias gss='git status -s'
alias gct='git commit'
alias gctm='git commit -m'
alias gamend='git commit --amend'
alias gd='git d'
alias gl='git ls'
alias gll='git lodag'
alias glll='git hist'
alias gal='git llog'
alias gsl='git s && git ls'
alias gls='git ls && git s'

alias dw='cd ~/Downloads'
alias dk='cd ~/Desktop'
alias dc='cd ~/Documents'
alias img='cd ~/Pictures'

alias a='apps'

alias bluetooth='blueman-applet & blueman-manager'
alias audio='pavucontrol'
alias mongoon='sudo mongod --config /etc/mongod.conf'

alias nvimswap='cd /home/dev/.local/state/nvim/swap'

alias r='ranger'
alias open='thunar'
alias nv='git pull && nvim .'
alias w='curl wttr.in'
alias weather='curl wttr.in'
alias bat='batcat --style=numbers --color=always'
alias man2='tldr'
alias fzf='fzf --reverse --inline-info --height 100%'
alias fd='fdfind'
alias copyme='xclip -selection clipboard'
alias xme='xclip -selection clipboard'
alias hurl='cat | grep -Eo $URL_REGEX | tr " " "\n" | fzf'
alias xurl='hurl | copyme'
alias surl='hurl | xargs surf'
alias furl='hurl | xargs firefox-esr'
alias fpurl='hurl | xargs firefox-esr --private-window'
alias wurl='hurl | xargs wget'
alias cpwd='pwd | copyme'

alias ggit='lazygit'
alias ddocker='lazydocker'
alias nn='lazynpm'
alias nr='npm run'
alias xampp='sudo /opt/lampp/manager-linux-x64.run'

alias ethernetinterface='nmcli device status | grep ethernet | cut -d " " -f1 | head -1'

alias wifiset='nvim /etc/network/interfaces'
alias wifishow='cat /etc/network/interfaces'

# alias wifiip see function wifiip
alias wifilast='grep -A1 ssid /etc/network/interfaces | tr -d "\t"'
alias wifihistory='cat /etc/network/.networks'
alias wifiinterface='nmcli device status | grep wifi | cut -d" " -f1 | head -1'
alias wifiscan='sudo ip link set wlo1 up && sudo iwlist wlo1 scan | grep SSID | cut -d: -f2 | tr -d " \"" | sort | uniq'
alias wifioff='sudo ifdown $(wifiinterface) && wifidisable && refreshdbar'
alias wifienable='sudo kill -9 $(pgrep wpa_supplicant) || true && sleep 1 && sudo rfkill unblock wlan && sleep 1 && refreshdbar'
alias wifidisable='sudo rfkill block wlan && sleep 1 && refreshdbar'
alias wifion='wifienable && sudo ifup $(wifiinterface) && refreshdbar'
alias wifireset='sudo kill -9 $(pgrep wpa_supplicant) || true && sudo rfkill unblock wlan && sleep 1 && sudo ifdown $(wifiinterface) && sleep 1 && sudo ifup $(wifiinterface) && refreshdbar'
alias wificheck='ping -c 1 -s 1 www.debian.org'
alias wifiinfo='iw dev'
alias wifistatus='iw dev $(wifiinterface) link'
alias wifissid='iw dev | grep ssid | xargs | sed "s/ssid //"'
alias wifihelp='grep "alias wifi" ~/.bash_aliases | cut -c 7- | grep -v wifihelp | grep wifi'

alias screen="xrandr | grep ' connected' | cut -d' ' -f1"
alias dr='xrandr --output $(screen) --rotate right'
alias dl='xrandr --output $(screen) --rotate left'
alias dn='xrandr --output $(screen) --rotate normal'
alias di='xrandr --output $(screen) --rotate inverted'

alias dbarshow='eval $(ls ~/.bash_scripts/dbar/ | sed "s/*//g" | grep -v dbarshow | sed "s/^/dbar_/g" | xargs | sed "s/ / \&\& /g")'

alias cfish='cd ~/.config/fish && nv'
alias cdmenu='cd ~/.config/dmenu/ && nv'
alias cdwm='cd ~/.config/dwm/ && nv'
alias cdbar='cd ~/.config/dbar/ && nv'
alias cdshortcuts='cd ~/.config/dshortcuts/ && nv'
alias cslock='cd ~/.config/slock/ && nv'
alias cst='cd ~/.config/st/ && nv'
alias csurf='cd ~/.config/surf/ && nv'

alias ufish='source ~/.config/fish/config.fish'
alias udmenu='cd ~/.config/dmenu/ && sudo touch config.h && sudo rm config.h && sudo make clean install && sudo dos2unix /usr/local/bin/dmenu_run && sudo dos2unix /usr/local/bin/dmenu_path && sudo dos2unix /usr/local/bin/dmenu_run_desktop && sudo dos2unix /usr/local/bin/dmenu_path_desktop'
alias udwm='cd ~/.config/dwm/ && sudo touch config.h && sudo rm config.h && sudo make clean install'
alias udbar='cd ~/.config/dbar/ && sudo touch config.h && sudo rm config.h && sudo make clean install'
alias udshortcuts='cd ~/.config/dshortcuts/ && sudo touch config.h && sudo rm config.h && sudo make clean install'
alias uslock='cd ~/.config/slock/ && sudo touch config.h && sudo rm config.h && sudo make clean install'
alias ust='cd ~/.config/st/ && sudo touch config.h && sudo rm config.h && sudo make clean install'
alias usurf='cd ~/.config/surf/ && sudo touch config.h && sudo rm config.h && sudo make clean install'
