#!/bin/bash

option_1=''
option_2=''
last_selection=0

run_rofi() {
    local get_volume=$(pulsemixer --get-volume | cut -d' ' -f1)
    local get_mute=$(pulsemixer --get-mute | sed s/0/Unmute/ | sed s/1/Mute/)
    echo -e "$option_1\n$option_2" | rofi -dmenu \
        -mesg "Brightness : $(xrandr --verbose | grep -i brightness | awk '{print $2 *100}' | bc)%" \
        -kb-cancel Escape,Control+c \
        -kb-row-up "Alt+j" \
        -kb-row-down "Alt+k" \
        -markup-rows \
        -selected-row "$last_selection" \
        -theme "~/.bash_scripts/rasi/volume.rasi"
}

while true; do
    option=$(run_rofi)
    # Check if the option is empty (Rofi closed without selection)
    if [ -z "$option" ]; then
        break
    fi
    case $option in
    $option_1)
        eval 'fish -c "b0 notify"'
        last_selection=0
        ;;
    $option_2)
        eval 'fish -c "b1 notify"'
        last_selection=1
        ;;
    esac
done
