#!/bin/bash

rofi \
    -show drun \
    -kb-cancel Escape,Control+c \
    -kb-row-up "Alt+k" \
    -kb-row-down "Alt+j" \
    -kb-row-left "Alt+h" \
    -kb-row-right "Alt+l" \
    -theme "~/.bash_scripts/rasi/rofi.rasi"
