#!/bin/bash

main() {
    local layout_1="[]="
    local layout_2="M[]"
    local layout_3="@[]"
    local layout_4="/[]"
    local layout_5="H[]"
    local layout_6="TTT"
    local layout_7="==="
    local layout_8="HHH"
    local layout_9="###"
    local layout_10="---"
    local layout_11=":::"
    local layout_12="|M|"
    local layout_13=">M>"
    local layout_14="><>"
    local options="$layout_1\n$layout_2\n$layout_3\n$layout_4\n$layout_5\n$layout_6\n$layout_7\n$layout_8\n$layout_9\n$layout_10\n$layout_11\n$layout_12\n$layout_13\n$layout_14"

    local value="$(echo -e "$options" | rofi -dmenu \
        -mesg "Layout" \
        -kb-cancel Escape,Control+c \
        -kb-row-up "Alt+k" \
        -kb-row-down "Alt+j" \
        -kb-row-left "Alt+h" \
        -kb-row-right "Alt+l" \
        -theme "~/.bash_scripts/rasi/layout.rasi")"

    case $value in
    $layout_1) fish -c "fsignal 14" ;;
    $layout_2) fish -c "fsignal 1" ;;
    $layout_3) fish -c "fsignal 2" ;;
    $layout_4) fish -c "fsignal 3" ;;
    $layout_5) fish -c "fsignal 4" ;;
    $layout_6) fish -c "fsignal 5" ;;
    $layout_7) fish -c "fsignal 6" ;;
    $layout_8) fish -c "fsignal 7" ;;
    $layout_9) fish -c "fsignal 8" ;;
    $layout_10) fish -c "fsignal 9" ;;
    $layout_11) fish -c "fsignal 10" ;;
    $layout_12) fish -c "fsignal 11" ;;
    $layout_13) fish -c "fsignal 12" ;;
    $layout_14) fish -c "fsignal 13" ;;
    esac
}

main "$@"
