#!/bin/bash

option_1=' '
option_2=''
last_selection=0

run_rofi() {
    local options=$(echo -e "$option_1\n$option_2")
    echo -e "$options" | rofi -dmenu \
        -mesg "Microphone ($(fish -c microstatus))" \
        -kb-cancel Escape,Control+c \
        -kb-row-up "Alt+k" \
        -kb-row-down "Alt+j" \
        -kb-row-left "Alt+h" \
        -kb-row-right "Alt+l" \
        -selected-row "$last_selection" \
        -theme "~/.bash_scripts/rasi/microphone.rasi"
}

while true; do
    option=$(run_rofi)
    # Check if the option is empty (Rofi closed without selection)
    if [ -z "$option" ]; then
        break
    fi

    case $option in
    $option_1)
        fish -c "m0 notify"
        break
        ;;
    $option_2)
        fish -c "m1 notify"
        break
        ;;
    esac
done
