#!/bin/bash

option_1=''
option_2=''
option_3=''
option_4=''
option_5=''

run_rofi() {
    echo -e "$option_1\n$option_2\n$option_3\n$option_4\n$option_5\n$option_6" | rofi -dmenu \
        -mesg "$(hostname) ($(whoami)) Uptime : $(uptime -p | sed -e 's/up //g')" \
        -kb-cancel Escape,Control+c \
        -kb-row-up "Alt+k" \
        -kb-row-down "Alt+j" \
        -kb-row-left "Alt+h" \
        -kb-row-right "Alt+l" \
        -theme "~/.bash_scripts/rasi/power.rasi"
}

confirm_run_yes() {
    local yes=''
    local no=''
    selected="$(echo -e "$yes\n$no" | rofi -dmenu \
        -mesg 'Are you Sure?' \
        -selected-row 2 \
        -no-click-to-exit \
        -kb-cancel Escape,Control+c \
        -kb-row-up "Alt+k" \
        -kb-row-down "Alt+j" \
        -kb-row-left "Alt+h" \
        -kb-row-right "Alt+l" \
        -theme "~/.bash_scripts/rasi/confirm.rasi")"

    if [[ "$selected" == "$yes" ]]; then
        ${@}
    else
        exit
    fi
}

confirm_run_no() {
    local yes=''
    local no=''
    selected="$(echo -e "$yes\n$no" | rofi -dmenu \
        -mesg 'Are you Sure?' \
        -selected-row 1 \
        -no-click-to-exit \
        -kb-cancel Escape,Control+c \
        -kb-row-up "Alt+k" \
        -kb-row-down "Alt+j" \
        -kb-row-left "Alt+h" \
        -kb-row-right "Alt+l" \
        -theme "~/.bash_scripts/rasi/confirm.rasi")"

    if [[ "$selected" == "$yes" ]]; then
        ${@}
    else
        exit
    fi
}

case $(run_rofi) in
$option_1) confirm_run_yes 'fish -c "ssuspend"' ;;
$option_2) confirm_run_yes 'fish -c "sslock"' ;;
$option_3) confirm_run_no 'systemctl shutdown now' ;;
$option_4) confirm_run_no 'systemctl reboot' ;;
$option_5) confirm_run_no 'fish -c "pkilldwm"' ;;
esac
