#!/bin/bash

option_1='r'
option_2='L'
option_3='n'
option_4='i'
last_selection=0

run_rofi() {
    echo -e "$option_1\n$option_2\n$option_3\n$option_4" | rofi -dmenu \
        -mesg "Rotation" \
        -kb-cancel Escape,Control+c \
        -kb-row-up "Alt+k" \
        -kb-row-down "Alt+j" \
        -kb-row-left "Alt+h" \
        -kb-row-right "Alt+l" \
        -selected-row "$last_selection" \
        -theme "~/.bash_scripts/rasi/rotation.rasi"
}

while true; do
    option=$(run_rofi)
    # Check if the option is empty (Rofi closed without selection)
    if [ -z "$option" ]; then
        break
    fi
    case $option in
    $option_1)
        eval 'fish -c "dr"'
        last_selection=0
        ;;
    $option_2)
        eval 'fish -c "dl"'
        last_selection=1
        ;;
    $option_3)
        eval 'fish -c "dn"'
        last_selection=1
        ;;
    $option_4)
        eval 'fish -c "di"'
        last_selection=1
        ;;
    esac
done
