#!/bin/sh

battery_capacity=$(cat /sys/class/power_supply/BAT1/capacity)
battery_status=$(cat /sys/class/power_supply/BAT1/status)
battery_color=''
battery_icon=''

if [ "$battery_status" = 'Charging' ]; then
    battery_color='\x11'
    battery_symbol=''
elif [ "$battery_status" = 'Discharging' ]; then
    battery_symbol=''
    if [ "$battery_capacity" -gt 80 ]; then
        battery_color='\x20'
    elif [ "$battery_capacity" -gt 70 ]; then
        battery_color='\x16'
    elif [ "$battery_capacity" -gt 60 ]; then
        battery_color='\x0e'
    elif [ "$battery_capacity" -gt 50 ]; then
        battery_color='\x0d'
    elif [ "$battery_capacity" -gt 40 ]; then
        battery_color='\x0c'
    elif [ "$battery_capacity" -gt 30 ]; then
        battery_color='\x0b'
    elif [ "$battery_capacity" -gt 20 ]; then
        battery_color='\x05'
    elif [ "$battery_capacity" -gt 10 ]; then
        battery_color='\x04'
        fish -c 'setbrightness 20'
    else
        battery_color='\x03'
        fish -c 'setbrightness 20'
    fi
elif [ "$battery_status" = 'Full' ]; then
    battery_color='\x13'
    battery_symbol=''
fi

echo -e "$battery_color$battery_icon $battery_capacity $battery_symbol\x01"
