#!/bin/sh

battery_capacity=$(cat /sys/class/power_supply/BAT1/capacity)
battery_status=$(cat /sys/class/power_supply/BAT1/status)
battery_color=''
battery_icon=''

if [ "$battery_status" = 'Charging' ]; then
    battery_color='\x15'
    battery_symbol=''
elif [ "$battery_status" = 'Discharging' ]; then
    battery_symbol=''
    if [ "$battery_capacity" -lt 15 ]; then
        fish -c 'setbrightness 20'
        battery_color='\x03'
    elif [ "$battery_capacity" -lt 20 ]; then
        fish -c 'setbrightness 35'
        battery_color='\x04'
    elif [ "$battery_capacity" -lt 30 ]; then
        battery_color='\x05'
    elif [ "$battery_capacity" -lt 40 ]; then
        battery_color='\x0c'
    elif [ "$battery_capacity" -lt 50 ]; then
        battery_color='\x0d'
    elif [ "$battery_capacity" -lt 60 ]; then
        battery_color='\x0e'
    else
        battery_color='\x20'
    fi
elif [ "$battery_status" = 'Full' ]; then
    battery_color='\x14'
    battery_symbol=''
fi

echo -e "$battery_color $battery_icon $battery_capacity $battery_symbol \x01"
