#!/bin/sh

is_block=$(rfkill | grep bluetooth | awk '{print $4}')
if [ "$is_block" = "unblocked" ]; then
    icon_status=""
else
    icon_status=""
fi

icon_bluetooth=""

echo "$icon_bluetooth $icon_status"
