#!/bin/bash

sum_temperatures=0
count=0
temperature_icon=''
temperature_color=''

# Loop through all temperature files in thermal_zone
for zone in /sys/class/thermal/thermal_zone*; do
    # Check if the temp file exists and is a regular file
    if [ -f "$zone/temp" ]; then
        # Read the temperature and convert it to Celsius
        temp=$(cat "$zone/temp")
        # Divide by 1000 to convert to degrees Celsius
        temp_celsius=$(echo "scale=1; $temp / 1000" | bc)

        # Add the temperature to the sum and increment the count
        sum_temperatures=$(echo "$sum_temperatures + $temp_celsius" | bc)
        count=$((count + 1))
    fi
done

# Calculate the average
if [ $count -gt 0 ]; then
    average=$(echo "scale=1; $sum_temperatures / $count" | bc)
    average_int=$(echo "$average" | awk '{printf "%d", $1}') # Redondear a entero

    if [[ "$average_int" -gt 40 ]]; then
        temperature_color='\x03'
    elif [[ "$average_int" -gt 39 ]]; then
        temperature_color='\x04'
    elif [[ "$average_int" -gt 38 ]]; then
        temperature_color='\x0b'
    elif [[ "$average_int" -gt 37 ]]; then
        temperature_color='\x0c'
    elif [[ "$average_int" -gt 36 ]]; then
        temperature_color='\x0d'
    elif [[ "$average_int" -gt 35 ]]; then
        temperature_color='\x0e'
    elif [[ "$average_int" -gt 34 ]]; then
        temperature_color='\x15'
    else
        temperature_color='\x16'
    fi

    echo -e "$temperature_color$temperature_icon$average°C\x01"
else
    echo -e "$temperature_color$temperature_icon ERROR\x01"
fi
