#!/bin/sh

updates_status=$(apt list --upgradable 2>/dev/null | grep "upgradable" | wc -l)
updates_icon=''

if [ "$updates_status" -gt 0 ]; then
    updates_color="\x03"
    # else
    # updates_color="\x09"
fi

echo -e "$updates_color $updates_icon $updates_status \x01"
