#!/bin/bash

# function to launch applications from .desktop files
apps() {
    local command=$(ls /usr/share/applications/*.desktop | sed 's/\.desktop$//g' | sed 's/^\/usr\/share\/applications\///g' | fzf)

    if [[ -n "$command" ]]; then
        # launch the selected application
        gtk-launch "$command"
        exit
    else
        echo "Aborted!"
    fi
}

apps
