#!/bin/bash

# function to launch applications from .desktop files
apps() {
    local command=$(cd '/usr/share/applications' && ls *.desktop | sed 's/\.desktop$//g' | fzf)

    if [[ -n "$command" ]]; then
        # launch the selected application
        gtk-launch "$command"
        exit
    else
        echo "Aborted!"
    fi
}

apps
