#!/bin/bash
# TODO: use screen alias

# function to decrease 10% the brightness of the screen
b0() {

    local option="${1:-terminal}"
    local screens=$(xrandr | grep ' connected' | cut -d' ' -f1)

    # get the current brightness value
    local current_brightness=$(xrandr --verbose | grep -i brightness | cut -f2 -d " " | head -n 1)

    local new_brightness=$(echo "$current_brightness - 0.1" | bc)

    # ensure the new brightness is not less than 0.1
    if (($(echo "$new_brightness < 0.1" | bc -l))); then
        new_brightness=0.1
    fi

    for screen in $screens; do
        xrandr --output "$screen" --brightness "$new_brightness"
    done

    local text=$(echo "$new_brightness" | xargs -I {} echo {} "*100" | bc | cut -d. -f1)
    source ~/.bash_scripts/globals/msg "Brightness" "$text%" "$option"
}

b0 "$@"
