#!/bin/bash

b1() {
    # TODO: use screen alias
    screen=$(xrandr | grep ' connected' | cut -d' ' -f1)

    current_brightness=$(xrandr --verbose | grep -i brightness | cut -f2 -d " " | head -n 1)

    new_brightness=$(echo "$current_brightness + 0.1" | bc)

    # Ensure the new brightness is not more than 1
    if (($(echo "$new_brightness > 1" | bc -l))); then
        new_brightness=1
    fi

    xrandr --output "$screen" --brightness "$new_brightness"
    xrandr --verbose | grep Brightness | xargs

    source ~/.bash_scripts/globals/refreshdbar
}

b1
