#!/bin/bash
# TODO: use screen alias
# TODO: use refreshdbar function

# function to decrease 10% the brightness of the screen
b1() {

    local option="${1:-terminal}"
    local refreshdbar="${2:-false}"
    local screen=$(xrandr | grep ' connected' | cut -d' ' -f1)

    # get the current brightness value
    local current_brightness=$(xrandr --verbose | grep -i brightness | cut -f2 -d " " | head -n 1)

    local new_brightness=$(echo "$current_brightness + 0.1" | bc)

    # ensure the new brightness is not more than 1
    if (($(echo "$new_brightness > 1" | bc -l))); then
        new_brightness=1
    fi

    xrandr --output "$screen" --brightness "$new_brightness"

    local text=$(echo "$new_brightness" | xargs -I {} echo {} "*100" | bc | cut -d. -f1)
    source ~/.bash_scripts/globals/msg "Brightness" "$text%" "$option"
    if [[ "$refreshdbar" = "true" ]]; then
        source ~/.bash_scripts/globals/refreshdbar
    fi
}

b1 "$@"
