#!/bin/bash

# function to find aliases using fzf
falias() {
    # read the alias file, remove empty lines and duplicates, and pass to fzf
    local command=$(sed '/^$/d' ~/.bash_aliases | awk '!seen[$0]++' | fzf)

    local current_command=$(echo "$command" | awk -F'=' '{print $2}' | tr -d "'")

    if [[ -n "$current_command" ]]; then
        echo -e "\n$command\n"
        echo -e ".eval: $current_command\n"

        fish -c eval "$current_command"
    else
        echo "Aborted!"
    fi
}

falias
