#!/bin/bash

# function to find files by name
ffind() {
    local name="$1"
    local path="${2:-/}"

    if [[ -n "$name" ]]; then
        find $(echo "$path") -name "$name" 2>/dev/null
    else
        echo "Aborted! You did not provide any argument."
    fi
}

ffind "$@"
