#!/bin/bash

# function to search command history using fzf
fhistory() {
    # get the command from history, excluding the 'fh' command itself
    command=$(fish -c history | grep -v '^ *[0-9]* *fh' | sed '/^$/d' | awk '!seen[$0]++' | fzf)

    if [[ -n "$command" ]]; then
        echo -e "\n$command\n"
        echo -e "eval: $command\n"
        eval "$command"
    else
        echo "Aborted!"
    fi
}

fhistory
