#!/bin/bash

# function to kill dbar (dwm environments)
killdbar() {
    if [ -f /tmp/dbar_pid ]; then
        kill $(cat /tmp/dbar_pid)
        rm /tmp/dbar_pid # Opcional
        if ! pgrep -x "dwm" >/dev/null; then
            xsetroot -name " "
        fi
    fi
}

killdbar
