#!/bin/bash

# function to mute microphone
m0() {
    local option="${1:-terminal}"

    pactl set-source-mute $(fish -c micro) 1

    source ~/.bash_scripts/globals/msg "Microphone" "$(fish -c microstatus)" "$option"
}

m0 "$@"
