#!/bin/bash

# function to unmute microphone
m1() {
    local option="${1:-terminal}"

    pactl set-source-mute $(fish -c micro) 0

    source ~/.bash_scripts/globals/msg "Microphone" "$(fish -c microstatus)" "$option"
}

m1 "$@"
