#!/bin/bash

# function to simulate a ranger command
rr() {
    local precommand=$(ls -la | sed '1,2d')

    local command=$(printf "%s\n" "$precommand" | fzf --height 90% --preview "echo {} | awk '{print \$9}' | xargs -I {} batcat --style=numbers --color=always {}")

    local type=$(echo "$command" | cut -c1)
    local name=$(echo "$command" | awk '{print $9}')

    if [[ -z "$type" ]]; then
        echo "Aborted!"
        exit 0
    fi

    if [[ "$type" == "-" ]]; then
        eval_commmand "nvim" "$name"
    elif [[ "$type" == "d" ]]; then
        cd "$name"
        rr
    elif [[ "$type" == "l" ]]; then
        eval_commmand "nvim" "$name"
    fi
}

eval_commmand() {
    local $name=$1
    local $action=$2
    echo -e "\neval: $action $name\n"
    eval "$(echo $action) $name"
}

rr
