#!/bin/bash
# TODO: use refreshdbar function

# function decrease 10% the sound
s0() {

    local option="${1:-terminal}"
    local current_volume=$(pulsemixer --get-volume | cut -d' ' -f1)
    local new_volumen=$(echo "$current_volume" - 10 | bc)
    local get_mute=$(pulsemixer --get-mute | sed s/1/Unmute/ | sed s/0/Mute/)
    pulsemixer --set-volume "$new_volumen"

    source ~/.bash_scripts/globals/msg "Sound $get_mute" "$new_volumen%" "$option"
    source ~/.bash_scripts/globals/refreshdbar
}

s0 "$1"
