#!/bin/bash
# TODO: use refreshdbar function

# function increase 10% the sound
s1() {

    local option="${1:-terminal}"
    local current_volume=$(pulsemixer --get-volume | cut -d' ' -f1)
    local new_volumen=$(echo "$current_volume" + 10 | bc)

    if [ "$new_volumen" -gt 100 ]; then
        new_volumen=100
    fi

    local get_mute=$(pulsemixer --get-mute | sed s/0/Unmute/ | sed s/1/Mute/)
    pulsemixer --set-volume "$new_volumen"

    source ~/.bash_scripts/globals/msg "Sound $get_mute" "$new_volumen%" "$option"
    source ~/.bash_scripts/globals/refreshdbar
}

s1 "$1"
