#!/bin/bash

# function to set sound
setsound() {

    local value=$1
    local option="${2:-terminal}"
    local refreshdbar="${3:-false}"

    # Check if the value is less than 0 or greater than 100
    if [[ $value -lt 0 || $value -gt 100 ]]; then
        echo "The value has to be between 0 & 100."
        return 1
    fi

    local get_mute=$(pulsemixer --get-mute | sed s/0/Unmute/ | sed s/1/Mute/)
    pulsemixer --set-volume "$value"

    source ~/.bash_scripts/globals/msg "Sound $get_mute" "$value%" "$option"
    if [[ "$refreshdbar" -eq true ]]; then
        source ~/.bash_scripts/globals/refreshdbar
    fi
}

setsound "$@"
