#!/bin/bash

# function to set sound
setsound() {

    local value=$1
    local option="${2:-terminal}"

    # Check if the value is less than 0 or greater than 100
    if [[ $value -lt 0 || $value -gt 100 ]]; then
        echo "The value has to be between 0 & 100."
        return 1
    fi

    pulsemixer --set-volume "$value"

    source ~/.bash_scripts/globals/msg "Sound" "$value%" "$option"
    source ~/.bash_scripts/globals/refreshdbar
}

setsound "$@"
