#!/bin/bash
# TODO: use refreshdbar function

# function mute the sound
smute() {

    local option="${1:-terminal}"
    local refreshdbar="${2:-false}"
    local current_volume=$(pulsemixer --get-volume | cut -d' ' -f1)
    pulsemixer --mute

    source ~/.bash_scripts/globals/msg "Sound Mute" "$current_volume%" "$option"
    if [[ "$refreshdbar" -eq true ]]; then
        source ~/.bash_scripts/globals/refreshdbar
    fi
}

smute "$@"
