#!/bin/sh

msg() {
    source ~/.bash_scripts/globals/msg "$@"
}

prompt() {
    source ~/.bash_scripts/globals/prompt $prompt_type "$@"
}

main() {

    prompt_type="${1:-fzf}"
    msg_type="${2:-terminal}"
    local option=$(echo -e "j: Decrement Sound 10%\nk: Increment Sound 10%\n0: Set Sound in 0%\n1: Set Sound in 10%\n2: Set Sound in 20%\n3: Set Sound in 30%\n4: Set Sound in 40%\n5: Set Sound in 50%\n6: Set Sound in 60%\n7: Set Sound in 70%\n8: Set Sound in 80%\n9: Set Sound in 90%\no: Set Sound in 100%\nu: Sound unmute\nm: Sound mute" | prompt "Choose an option: ")
    local value=$(echo $option | cut -d: -f1)

    case "$value" in
    j) fish -c "s0           \"$msg_type\" " ;;
    k) fish -c "s1           \"$msg_type\" " ;;
    0) fish -c "setsound 0   \"$msg_type\" " ;;
    1) fish -c "setsound 10  \"$msg_type\" " ;;
    2) fish -c "setsound 20  \"$msg_type\" " ;;
    3) fish -c "setsound 30  \"$msg_type\" " ;;
    4) fish -c "setsound 40  \"$msg_type\" " ;;
    5) fish -c "setsound 50  \"$msg_type\" " ;;
    6) fish -c "setsound 60  \"$msg_type\" " ;;
    7) fish -c "setsound 70  \"$msg_type\" " ;;
    8) fish -c "setsound 80  \"$msg_type\" " ;;
    9) fish -c "setsound 90  \"$msg_type\" " ;;
    o) fish -c "setsound 100 \"$msg_type\" " ;;
    u) fish -c "sunmute      \"$msg_type\" " ;;
    m) fish -c "smute        \"$msg_type\" " ;;
    *) echo "Option no valid" ;;
    esac
}

main "$@"
