#!/bin/bash
# TODO: use refreshdbar function

# function to toggle mute sound
stogglemute() {

    local option="${1:-terminal}"
    pulsemixer --toggle-mute

    local text=$(pulsemixer --get-mute | sed s/1/Unmute/ | sed s/0/Mute/)
    source ~/.bash_scripts/globals/msg "Sound" "$text%" "$option"
    source ~/.bash_scripts/globals/refreshdbar
}

stogglemute "$1"
