#!/bin/bash

main() {
    # You can use rofi & fzf
    local prompt_type="${1:-fzf}"

    _msg "Getting list of available Wi-Fi networks..."
    wifi_list=$(nmcli --fields "SECURITY,SSID" device wifi list | sed 1d | sed 's/  */ /g' | sed -E "s/WPA*.?\S/ /g" | sed "s/^--/ /g" | sed "s/  //g" | sed "/--/d")

    connected=$(nmcli -fields WIFI g)
    if [[ "$connected" =~ "enabled" ]]; then
        toggle="󰖪  Disable Wi-Fi"
    elif [[ "$connected" =~ "disabled" ]]; then
        toggle="󰖩  Enable Wi-Fi"
    fi

    chosen_network=$(echo -e "$toggle\n$wifi_list" | uniq -u | prompt "$prompt_type" "Wi-Fi SSID: ")
    read -r chosen_id <<<"${chosen_network:3}"

    if [ -z "$chosen_network" ]; then
        exit
    elif [ "$chosen_network" = "󰖩  Enable Wi-Fi" ]; then
        rfkill unblock wlan && sleep 1 && nmcli radio wifi on
        source ~/.bash_scripts/globals/refreshdbar
    elif [ "$chosen_network" = "󰖪  Disable Wi-Fi" ]; then
        rfkill block wlan && sleep 1 && nmcli radio wifi off
        source ~/.bash_scripts/globals/refreshdbar
    else
        success_message="Wi-Fi SSID: \"$chosen_id\"."
        saved_connections=$(nmcli -g NAME connection)

        if [[ $(echo "$saved_connections" | grep -w "$chosen_id") = "$chosen_id" ]]; then
            update_password=$(echo -e "No\nYes" | prompt "$prompt_type" "Password for \"$chosen_id\" already saved. Do you want to update it?")

            if [[ "$update_password" == "Yes" ]]; then
                wifi_password=$(prompt "$prompt_type" "New Password: ")
                nmcli connection modify "$chosen_id" 802-11-wireless.psk "$wifi_password"
            fi

            nmcli connection up id "$chosen_id" | grep "successfully" && _msg "Connection Established" "$success_message"
            source ~/.bash_scripts/globals/refreshdbar
        else
            if [[ "$chosen_network" =~ "" ]]; then
                wifi_password=$(prompt "$prompt_type" "Password: ")
            fi
            nmcli device wifi connect "$chosen_id" password "$wifi_password" | grep "successfully" && _msg "Connection Established" "$success_message"
            source ~/.bash_scripts/globals/refreshdbar
        fi
    fi
}

_msg() {
    source ~/.bash_scripts/globals/msg "$@"
}

prompt() {
    if [ "$#" -ne 2 ]; then
        _msg "Error: prompt needs 2 parameters."
        return 1
    fi

    if [ "$1" = "fzf" ]; then
        fzf --height 50% --reverse --prompt "$2"
    elif [ "$1" = "rofi" ]; then
        rofi -dmenu -p "$2"
    else
        _msg "Error: Unsupported prompt type."
        return 1
    fi
}

main $1
