#!/bin/sh

# TODO: use fsignal

case "$1" in
j) fish -c 'b0 notify true' ;;
k) fish -c 'b1 notify true' ;;
1) fish -c 'setbrightness 10 notify true' ;;
2) fish -c 'setbrightness 20 notify true' ;;
3) fish -c 'setbrightness 30 notify true' ;;
4) fish -c 'setbrightness 40 notify true' ;;
5) fish -c 'setbrightness 50 notify true' ;;
6) fish -c 'setbrightness 60 notify true' ;;
7) fish -c 'setbrightness 70 notify true' ;;
8) fish -c 'setbrightness 80 notify true' ;;
9) fish -c 'setbrightness 90 notify true' ;;
o) fish -c 'setbrightness 100 notify true' ;;
esac
