#!/bin/sh

# TODO: use fsignal

case "$1" in
j) fish -c 'b0 notify' ;;
k) fish -c 'b1 notify' ;;
1) fish -c 'setbrightness 10 notify' ;;
2) fish -c 'setbrightness 20 notify' ;;
3) fish -c 'setbrightness 30 notify' ;;
4) fish -c 'setbrightness 40 notify' ;;
5) fish -c 'setbrightness 50 notify' ;;
6) fish -c 'setbrightness 60 notify' ;;
7) fish -c 'setbrightness 70 notify' ;;
8) fish -c 'setbrightness 80 notify' ;;
9) fish -c 'setbrightness 90 notify' ;;
o) fish -c 'setbrightness 100 notify' ;;
esac
