#!/bin/bash

internet() {
    local browser=$1
    local type=$2
    local goto=$3
    local option="${4:-both}"

    if [ "$#" -lt 3 ] || [ "$#" -gt 4 ]; then
        msg "Use: $0 " "<browser> <type> <goto>" "$option"
        exit 1
    fi

    case "$goto" in
    n) url="about:blank" ;;
    a) url="https://www.duckduckgo.com/?q=DuckDuckGo+AI+Chat&ia=chat&duckai=1" ;;
    d) url="https://www.duckduckgo.com" ;;
    g) url="https://www.google.com" ;;
    G) url="https://www.github.com/login" ;;
    m) url="https://www.gmail.com" ;;
    d) url="https://www.drive.google.com" ;;
    w) url="https://web.whatsapp.com" ;;
    s) url="https://open.spotify.com" ;;
    y) url="https://youtube.com" ;;
    e) url="https://translate.google.co.uk/?sl=en&tl=es&op=translate" ;;
    E) url="https://translate.google.co.uk/?sl=es&tl=en&op=translate" ;;
    *)
        msg "Option no valid" " " "$option"
        exit 1
        ;;
    esac

    case $browser in
    firefox-esr)
        if [ "$type" == "-p" ]; then
            firefox-esr --private-window "$url" &
        else
            firefox-esr "$url" &
        fi
        ;;
    qutebrowser)
        qutebrowser "$url" &
        ;;
    librewolf)
        if [ "$type" == "-p" ]; then
            librewolf --private-window "$url" &
        else
            librewolf "$url" &
        fi
        ;;
    brave-browser)
        if [ "$type" == "-p" ]; then
            brave-browser --incognito "$url" &
        else
            brave-browser "$url" &
        fi
        ;;
    surf)
        surf "$url" &
        ;;
    vieb)
        vieb "$url" &
        ;;
    *)
        msg "You can only use: " "firefox-esr, qutebrowser, librewolf, brave-browser or surf" "$option"
        exit 1
        ;;
    esac

    msg "$browser ($type)" "$url" "$option"
}

msg() {
    source ~/.bash_scripts/globals/msg "$@"
}

internet "$@"
